"""Add new intelligence models

Revision ID: 14d9c93ccd1e
Revises: 3fefa89a68e4
Create Date: 2026-10-08 22:04:26.027863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14d9c93ccd1e'
down_revision: Union[str, Sequence[str], None] = '3fefa89a68e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('local_track_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standing_query',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_query', sa.String(), nullable=False),
    sa.Column('structured_query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standing_query')
    op.drop_table('global_track')
    # ### end Alembic commands ###
