"""Update Camera fields

Revision ID: 3fefa89a68e4
Revises: 231e150172a6
Create Date: 2026-10-08 21:34:30.571267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fefa89a68e4'
down_revision: Union[str, Sequence[str], None] = '231e150172a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('description', sa.String(), nullable=True))
    op.add_column('camera', sa.Column('source_type', sa.String(), nullable=False))
    op.add_column('camera', sa.Column('location', sa.String(), nullable=True))
    op.add_column('camera', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('camera', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'updated_at')
    op.drop_column('camera', 'created_at')
    op.drop_column('camera', 'location')
    op.drop_column('camera', 'source_type')
    op.drop_column('camera', 'description')
    # ### end Alembic commands ###
