"""Add MVP tables

Revision ID: 6eea65785971
Revises: b9df236dec7f
Create Date: 2026-10-08 16:02:29.645775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eea65785971'
down_revision: Union[str, Sequence[str], None] = 'b9df236dec7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('clock_offset_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trajectory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('capture_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('global_identity_id', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('frame_ref', sa.String(), nullable=True),
    sa.Column('clip_ref', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['camera_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_attrs', 'event', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('ix_event_camera_time', 'event', ['camera_id', 'timestamp_start'], unique=False)
    op.create_index('ix_event_identity', 'event', ['global_identity_id'], unique=False)
    op.create_index('ix_event_track', 'event', ['track_id'], unique=False)
    op.create_index('ix_event_type', 'event', ['event_type'], unique=False)
    op.create_table('scene_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['camera_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_memory')
    op.drop_index('ix_event_type', table_name='event')
    op.drop_index('ix_event_track', table_name='event')
    op.drop_index('ix_event_identity', table_name='event')
    op.drop_index('ix_event_camera_time', table_name='event')
    op.drop_index('ix_event_attrs', table_name='event', postgresql_using='gin')
    op.drop_table('event')
    op.drop_table('video_file')
    op.drop_table('track')
    op.drop_table('camera_zone')
    op.drop_table('camera')
    op.drop_table('job')
    op.drop_table('gateway')
    # ### end Alembic commands ###
